# Generated by Django 6.1 on 2026-09-13 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente_validation', 'En attente de validation admin'), ('essai', "Période d'essai"), ('actif', 'Actif (payé)'), ('expire', 'Expiré')], default='en_attente_validation', max_length=25)),
                ('date_fin_essai', models.DateTimeField(blank=True, null=True)),
                ('date_fin_abonnement', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('gerant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('avance', 'Avance de réservation (PayTech)'), ('solde', 'Solde payé sur place'), ('abonnement', 'Abonnement gérant (PayTech)')], max_length=15)),
                ('montant', models.PositiveIntegerField()),
                ('moyen_paiement', models.CharField(blank=True, max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='paiements.abonnement')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservations.reservation')),
            ],
        ),
    ]
