# Generated by Django 6.1 on 2026-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='alerte_expiration_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
