# Generated by Django 6.1 on 2026-10-03 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_abonnement_alerte_expiration_envoyee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.CharField(choices=[('avance', 'Avance de réservation (PayTech)'), ('solde', 'Solde payé sur place'), ('abonnement', 'Abonnement gérant (PayTech)'), ('remboursement', "Remboursement de l'avance (annulation)")], max_length=15),
        ),
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=15)),
                ('numero', models.CharField(max_length=12)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('gerant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('operateur', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=15)),
                ('numero', models.CharField(max_length=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de versement'), ('verse', 'Versé'), ('echoue', 'Échoué')], default='en_attente', max_length=15)),
                ('methode', models.CharField(choices=[('manuelle', "Versement manuel par l'admin"), ('automatique', 'Versement automatique (API)')], default='manuelle', max_length=15)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('motif_echec', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
