# Generated by Django 6.1 on 2026-09-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('prix', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('prix_recommande_ia', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_attente', 'En attente de paiement'), ('confirme', 'Confirmé')], default='disponible', max_length=15)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='terrains.terrain')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('terrain', 'date', 'heure_debut')},
            },
        ),
    ]
