# Generated by Django 6.1 on 2026-09-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='derniere_maj_ia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creneau',
            name='niveau_demande',
            field=models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], max_length=10, null=True),
        ),
    ]
