# Generated by Django 6.1 on 2026-09-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneaux', '0002_creneau_derniere_maj_ia_creneau_niveau_demande'),
        ('terrains', '0003_terrain_nombre_portions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneau',
            options={'ordering': ['date', 'heure_debut', 'portion']},
        ),
        migrations.AlterUniqueTogether(
            name='creneau',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='creneau',
            name='portion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='creneau',
            unique_together={('terrain', 'date', 'heure_debut', 'portion')},
        ),
    ]
