# Generated by Django 6.1 on 2026-09-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Foot à 5', 'Foot à 5'), ('Foot à 6', 'Foot à 6'), ('Foot à 7', 'Foot à 7'), ('Foot à 11', 'Foot à 11')], max_length=20)),
                ('ville', models.CharField(choices=[('Dakar', 'Dakar'), ('Mermoz', 'Mermoz'), ('Guédiawaye', 'Guédiawaye'), ('Almadies', 'Almadies'), ('Yoff', 'Yoff'), ('Thiès', 'Thiès'), ('Saly', 'Saly'), ('Mbour', 'Mbour')], max_length=30)),
                ('adresse', models.CharField(max_length=255)),
                ('capacite', models.PositiveIntegerField(help_text='Nombre de joueurs')),
                ('surface', models.CharField(choices=[('Synthétique', 'Synthétique'), ('Gazon naturel', 'Gazon naturel'), ('Bitume', 'Bitume')], max_length=20)),
                ('prix_heure', models.PositiveIntegerField(help_text='Prix en FCFA par heure')),
                ('avance', models.PositiveIntegerField(default=5000, help_text='Avance à payer en FCFA')),
                ('heure_ouverture', models.TimeField(default='08:00')),
                ('heure_fermeture', models.TimeField(default='23:00')),
                ('equipements', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('gerant', models.ForeignKey(limit_choices_to={'role': 'gerant'}, on_delete=django.db.models.deletion.CASCADE, related_name='terrains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TerrainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='terrains/')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='terrains.terrain')),
            ],
        ),
    ]
