# Generated by Django 6.1 on 2026-09-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
