# Generated by Django 6.1 on 2026-09-30 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0002_alter_terrain_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='nombre_portions',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = terrain simple ; 2 à 6 = terrain divisible en autant de portions', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
