# Generated by Django 6.1 on 2026-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0003_terrain_nombre_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='prix_portion',
            field=models.PositiveIntegerField(blank=True, help_text="Prix d'une portion en FCFA par heure (terrain divisible)", null=True),
        ),
    ]
