# Generated by Django 6.1 on 2026-10-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0005_terrain_latitude_terrain_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
