# Generated by Django 6.1 on 2026-09-13 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creneaux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=15)),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('montant_avance', models.PositiveIntegerField()),
                ('montant_total', models.PositiveIntegerField()),
                ('moyen_paiement', models.CharField(blank=True, max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('amateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='creneaux.creneau')),
            ],
        ),
    ]
