# Generated by Django 6.1 on 2026-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
