# Generated by Django 6.1 on 2026-10-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_commande_reservation_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='annule_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
