# Generated by Django 6.1 on 2026-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ville_preferee',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
