# Generated by Django 6.1 on 2026-09-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_telephone_user_ville_preferee'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
