# Generated by Django 6.1 on 2026-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('amateur', 'Amateur'), ('gerant', 'Gérant'), ('employe', 'Employé'), ('admin', 'Admin')], default='amateur', max_length=10),
        ),
    ]
