# Generated by Django 6.1 on 2026-09-13 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeGerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complexe', models.CharField(max_length=150)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='demandes_gerant/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_gerant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
