# Generated by Django 6.1 on 2026-10-05 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_employe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(max_length=310)),
                ('action', models.CharField(choices=[('ticket_valide', 'Ticket validé'), ('solde_encaisse', 'Solde encaissé'), ('reservation_annulee', 'Réservation annulée'), ('creneaux_crees', 'Créneaux créés'), ('creneaux_modifies', 'Créneaux modifiés'), ('creneaux_supprimes', 'Créneaux supprimés'), ('employe_ajoute', 'Employé ajouté'), ('employe_desactive', 'Employé désactivé'), ('employe_reactive', 'Employé réactivé')], max_length=25)),
                ('description', models.CharField(max_length=500)),
                ('cible', models.CharField(blank=True, max_length=150)),
                ('nombre', models.PositiveIntegerField(default=1)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_equipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mis_a_jour_le'],
                'indexes': [models.Index(fields=['proprietaire', '-mis_a_jour_le'], name='gerant_jour_proprie_b0d9c8_idx')],
            },
        ),
    ]
