# Generated by Django 6.1 on 2026-10-05 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reservation', 'Nouvelle réservation'), ('annulation', 'Réservation annulée'), ('avis', 'Avis'), ('retrait', 'Retrait'), ('abonnement', 'Abonnement'), ('alerte', 'Alerte'), ('terrain', 'Nouveau terrain'), ('inscription', 'Nouvelle inscription')], max_length=15)),
                ('titre', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=500)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['destinataire', '-cree_le'], name='notificatio_destina_f75fc6_idx')],
            },
        ),
    ]
